@echo off
echo Initializing git repository...
git init
echo Adding all files...
git add .
echo Committing changes...
git commit -m "Initial commit"
echo Setting up remote...
git remote add origin https://github.com/nonshas20/hmnight.git
echo Pushing to GitHub...
git push -u origin master
echo Done!
